AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Create ECS Task Definition for Coralogix logging agent.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-ECS
    Description: Create ECS Task Definition for Coralogix logging agent.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - ecs
      - agent
      - task
      - fluentd
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
Parameters:
  CoralogixRegion:
    Type: String
    Description: The Coralogix location region
    AllowedValues:
      - Europe
      - India
    Default: Europe
  PrivateKey:
    Type: String
    Description: The Coralogix private key which is used to validate your authenticity
    AllowedPattern: '[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}'
    ConstraintDescription: The PrivateKey should be valid UUID string
    MinLength: 36
    MaxLength: 36
    NoEcho: true
  ApplicationName:
    Type: String
    Description: The name of your application
    MaxLength: 64
    Default: ECS
Mappings:
  CoralogixRegionMap:
    Europe:
      LogUrl: https://api.coralogix.com/api/v1/logs
      TimeDeltaUrl: https://api.coralogix.com/sdk/v1/time
    India:
      LogUrl: https://api.app.coralogix.in/api/v1/logs
      TimeDeltaUrl: https://api.app.coralogix.in/sdk/v1/time
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: coralogix-ecs-agent
      RequiresCompatibilities:
        - EC2
      ContainerDefinitions:
        - Name: fluentd
          Image: docker.io/coralogixrepo/fluentd-coralogix-ecs:latest
          MemoryReservation: 512
          Environment:
            - Name: CORALOGIX_LOG_URL
              Value:
                Fn::FindInMap:
                  - CoralogixRegionMap
                  - Ref: CoralogixRegion
                  - LogUrl
            - Name: CORALOGIX_TIME_DELTA_URL
              Value:
                Fn::FindInMap:
                  - CoralogixRegionMap
                  - Ref: CoralogixRegion
                  - TimeDeltaUrl
            - Name: PRIVATE_KEY
              Value:
                Ref: PrivateKey
            - Name: APP_NAME
              Value:
                Ref: ApplicationName
          MountPoints:
            - SourceVolume: varlibdocker
              ContainerPath: /var/lib/docker
              ReadOnly: false
            - SourceVolume: varrundocker
              ContainerPath: /var/run/docker.sock
              ReadOnly: true
      Volumes:
        - Name: varlibdocker
          Host:
            SourcePath: /var/lib/docker
        - Name: varrundocker
          Host:
            SourcePath: /var/run/docker.sock
Outputs:
  CoralogixECSAgentTaskDefinitionArn:
    Description: Coralogix ECS Agent Task Definition ARN
    Value:
      Ref: TaskDefinition
    Export:
      Name: CORALOGIX-ECS-AGENT-TASK-DEFINITION-ARN